jaguaretekaasa/USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

jaguaretekaasa/catalogo/urls.py
from django.urls import path
from . import views

app_name = "catalogo"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:producto_id>', views.producto, name="producto"),
    path('producto_alta', views.producto_alta, name="producto_alta"),
    path('<int:producto_id>/producto_modificar', views.producto_modificar, name="producto_modificar"),
    path('<int:producto_id>/producto_eliminar', views.producto_eliminar, name="producto_eliminar"),
    path('resultado_busqueda', views.resultado_busqueda, name="resultado_busqueda"),
    path('<int:producto_id>/agregar_carrito', views.agregar_carrito, name="agregar_carrito"),
    path('<int:posicion>/quitar_carrito', views.quitar_carrito, name="quitar_carrito"),
    path('vaciar_carrito', views.vaciar_carrito, name="vaciar_carrito"),
    path('carrito', views.carrito, name="carrito"),
]

jaguaretekaasa/jaguaretekaasa/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', include('catalogo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('USUARIOS.urls')),
    path('acercade/', views.acercade, name="acercade")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguaretekaasa/catalogo/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=64)
    descripcion = models.CharField(max_length=120)

    def __str__(self):
        return f"{self.nombre} ({self.descripcion})"

class Producto(models.Model):
    titulo = models.CharField(max_length=64)
    imagen = models.ImageField (upload_to = 'fotos', blank = True)
    descripcion = models.CharField(max_length=120)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="productos")

    def __str__(self):
        return f"{self.titulo}: {self.imagen} {self.descripcion} - {self.precio} ({self.categoria})"

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, blank=True, related_name="productosDelCarrito")
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.usuario} - {self.total}"

class Image(models.Model):
         # Imagen
    img = models.ImageField(upload_to='img')
         # Tiempo de creación
    time = models.DateTimeField(auto_now_add=True)

jaguaretekaasa/catalogo/forms.py
from django import forms
from django.forms import fields
from .models import Producto, Categoria

class FormProductoCustom(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
    titulo = forms.CharField(label='Título:',max_length=64,
                                    widget=forms.TextInput(
                                    attrs={
                                        'class':'form-control',
                                        'placeholder':'Nombre del producto',
                                    }), required=True)
    imagen = forms.ImageField(label='Imagen:',
                                widget=forms.FileInput(
                                attrs={
                                    'class':'form-control',
                                    'placeholder':'Foto del producto',
                                }), required=True)
    descripcion = forms.CharField(label='Descripción:',max_length=64,
                                widget=forms.Textarea(
                                attrs={
                                    'class':'form-control',
                                    'placeholder':'Descripción del producto',
                                }), required=True)
    precio = forms.DecimalField(label='Precio:',max_value=100000, decimal_places=2, min_value=0,
                                widget=forms.NumberInput(
                                attrs={
                                    'class':'form-control',
                                    'placeholder':'Precio del producto',
                                }), required=True)
    categoria = forms.ModelChoiceField(queryset= Categoria.objects.all(), empty_label="(Nada)",label='Categoría:',
                                widget=forms.Select(
                                attrs={
                                    'class':'form-control',
                                }), required=True) 

jaguaretekaasa/catalogo/views.py
from django.forms.models import modelform_factory
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from .models import Producto, Categoria
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
#para cargar imagenes
from .models import Image
from django.shortcuts import HttpResponse
import json
import uuid
from django.db.models import Q
 
 
MEDIA_SERVER = 'http://127.0.0.1:8000/media/'
 
 

# Create your views here.

def index(request):
    
    if "carrito" not in request.session:
        request.session["carrito"] = []
    return render(request,"productos/index.html", {
        "lista_productos": Producto.objects.order_by('-id'),
        "carrito": request.session["carrito"],
    })


def producto(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    return render(request, "productos/producto.html", {
        "producto": producto,
    })

@permission_required('catalogo.add_producto')
def producto_alta(request):
    #ProductoForm = modelform_factory(Producto, fields=("titulo", "imagen", "descripcion", "precio", "categoria"))
    if request.method == "POST":
        form = FormProductoCustom(request.POST or None, request.FILES or None)
        
        

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("catalogo:index")) #nombre de la app: nombre de la ruta (urls.py)
        else:
            return render(request, "productos/producto_alta.html")
    else:
        form = FormProductoCustom()
        return render(request, "productos/producto_alta.html", {
            "formset": form
        })

@permission_required('catalogo.change_producto')
def producto_modificar(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    
    if request.method == "POST":     
        form = FormProductoCustom(request.POST, instance = un_producto) 
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("catalogo:index"))
    else:
        form = FormProductoCustom(instance = un_producto)
        return render(request, 'productos/producto_modificar.html', {
            "un_producto": un_producto,
            "formset": form
        })

@permission_required('catalogo.delete_producto')
def producto_eliminar(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    un_producto.delete()
    return HttpResponseRedirect(reverse("catalogo:index"))

def resultado_busqueda(request):
    search = request.GET.get('q')
    categorianombre = request.GET.get('categoriaelegida')
    if categorianombre != "":
        categoriaid = get_object_or_404(Categoria, nombre=categorianombre)
        productos = Producto.objects.filter(categoria_id = categoriaid.id)
        item = categorianombre
    else: 
        productos = Producto.objects.filter(Q(titulo__icontains=search) | Q(descripcion__icontains=search))
        item = search
    return render(request, "productos/resultado_busqueda.html",{
        "productos": productos,
        "item": item,
    })
@login_required
def carrito(request):
    carrito = []
    for producto_id in request.session["carrito"]:
        carrito.append(get_object_or_404(Producto, id=producto_id))
    return render(request, "productos/carrito.html",{
        'carrito': carrito,
    })

@login_required
def agregar_carrito(request, producto_id):
    request.session["carrito"] += [producto_id]
    return HttpResponseRedirect(reverse("catalogo:index"))

@login_required
def quitar_carrito(request, posicion):
    aux = []
    request.session["carrito"].pop(posicion-1)
    for elemento in request.session["carrito"]:
        aux.append(elemento)
    request.session["carrito"] = aux
    return HttpResponseRedirect(reverse("catalogo:carrito"))

@login_required
def vaciar_carrito(request):
    request.session["carrito"] = []
    return HttpResponseRedirect(reverse("catalogo:carrito"))

jaguaretekaasa/catalogo/templates/productos/carrito.html
{% extends "productos/layout.html" %}
{% block titulo %}
    <title>Mi carrito</title>
{% endblock %}
{% block content %}
<div class="container-fluid card"> 
    <div class="card-header">
        <h1>Productos del carrito</h1>
    </div>   
    <div class="container-fluid row card-body">
        <table class="responsive nowrap w-100">
            {% if carrito|length > 0 %}
                {% for un_producto in carrito %}
                    <tr>
                        <td>
                            <p>{{un_producto.titulo}}: {{un_producto.descripcion}} <span style="text-align: right;">$ {{un_producto.precio}}</span></p>
                        </td>
                        <td>
                            <a class= "btn btn-danger" href="{% url 'catalogo:quitar_carrito' forloop.counter %}">Quitar</a> 
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <h2>No tenés productos en tu carrito. <br> Ve al inicio para comprar ;) </h2>
            {% endif %}
        </table>
    </div>
    <div class="card-footer d-flex justify-content-end">
        <a class= "btn btn-danger" href="{% url 'catalogo:vaciar_carrito' %}">Vaciar carrito</a> 
        <button class="btn my-btn">Finalizar compra</button> 
    </div>
</div>    
{% endblock %}

jaguaretekaasa/catalogo/templates/productos/index.html
{% extends "productos/layout.html" %}
{% block titulo %}
    <title>Productos</title>
{% endblock %}
{% block h1 %}
    <h1>Productos</h1>
{% endblock %}
{% block content %}

    <div class="row"> 
        {% for un_producto in lista_productos %}
            {% if forloop.counter <= 3 %}
                <div class="col d-flex justify-content-center">
                    <div class="card" style="width: auto;"> 
                        <div class="card-header">
                            <h5 class="card-title">{{ un_producto.titulo }}</h5>
                        </div>
                        <div class="card-body">
                        {% load static %}
                        <img src="{{ un_producto.imagen.url }}" class="card-img-top" height="300" width="300" alt="foto">
                        </div>
                        <div class="card-footer mx-auto">
                            <a href="{% url 'catalogo:producto' un_producto.id %}" class="btn my-btn">Ver producto</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="container card my-3">
        <div class="card-header">
            <h1>Más productos</h1>
        </div>
        <div class="container-fluid row card-body">
            <table class="responsive nowrap w-100">
                {% for un_producto in lista_productos %}
                {% if forloop.counter > 3 and forloop.counter <= 10 %}
                <tr>
                    <td>
                        <a href="{% url 'catalogo:producto' un_producto.id %}">{{un_producto.titulo}}: {{un_producto.descripcion}}</a> 
                    </td>
                    <td>
                        {% if perms.catalogo.change_producto %}
                        <a class= "btn my-btn" href="{% url 'catalogo:producto_modificar' un_producto.id %}">Editar</a> 
                        {% endif %}
                        {% if perms.catalogo.delete_producto %} 
                        <a class= "btn btn-danger" href="{% url 'catalogo:producto_eliminar' un_producto.id %}">Eliminar</a>  
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>
        </div>
    </div>    

{% endblock %}

jaguaretekaasa/catalogo/templates/productos/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        {% block titulo %}
        {% endblock %}
        <meta name = "viewport" content = "width = device-width, initial-scale = 1.0">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="/style.css">

    </head>
    <body>
      <div class="superencabezado">
        <div class="navar navbar-expand">
          <div class="container-fluid navbar-nav encabezado">
              <div class="d-inline-block">
                  <img src="/fotos/Jaguaretekaa.png" width="25%" alt="logo">
              </div>
              <div class="top-right">
                <ul class="nav navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <p class="btn btn-outline-success">{{ user.get_username }}</p>
                  </li>
                  {% if request.user.groups.all.0.name == "usuario" %}
                    <li class="nav-item">
                      <a class="btn btn-outline-success position-relative" href="{% url 'catalogo:carrito'%}">
                        Carrito
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                          {{ request.session.carrito|length}}
                          <span class="visually-hidden">productos en el carrito</span>
                        </span>
                      </a>
                    </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="btn btn-outline-success" href="{% url 'logout'%}?next=/">Desconectarse</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                      <a class="btn btn-outline-success" href="{% url 'login'%}?next={{request.path}}">LOGIN</a>
                  </li>
                  <li class="nav-item">
                      <a class="btn btn-outline-success" href="{% url 'USUARIOS:registrarse' %}">REGISTRO</a>
                  </li>
                {% endif %}
                </ul>
              </div>
          </div>
        </div>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Jaguareté ka'a S.A.</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'catalogo:index' %}">Inicio</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Categorías
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% for c in categorias %}
                      <li><a class="dropdown-item">{{c.nombre}}</a></li>
                      {%endfor%}
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'acercade' %}">Acerca de...</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="mailto:jaguaretekaasa@gmail.com">Contacto</a>
                  </li>
                  <li class="nav-item">
                    {% if perms.catalogo.add_producto %}
                    <a class="nav-link" href="{% url 'catalogo:producto_alta'%}">Nuevo producto</a>
                    {% endif %}
                  </li>
                </ul>
              <form id="formulario" class="d-flex form-inline my-2 my-lg-0" action="{% url 'catalogo:resultado_busqueda' %}" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search" name="q" id="q">
                <input type="hidden" id="categoriaelegida" name="categoriaelegida">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
              </form>
            </div>
        </nav>
      </div>
        <main role="main" class="flex-shrink-0">
            <div class="container">
                <h1 class="mt-5">
                    {% block h1 %}
                    {% endblock %}
                </h1>
                <div class="container">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
          </main>
        <footer class="footer mt-auto py-3">
            <div class="container">
              <span class="text-muted">JAGUARETE KAA S.A. &copy; desarrollado por Mirian Rodriguez </span>
            </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script>
          $(document).on('click', '.dropdown-menu li a', function() {
              var cat = $(this).html();
              $('#categoriaelegida').attr("value", cat);
              document.getElementById("categoriaelegida").value = String(cat);
              document.getElementById("formulario").submit(); 
          }); 
        </script>
    </body>
</html>

jaguaretekaasa/catalogo/templates/productos/producto.html
{% extends "productos/layout.html" %}
{% block titulo %}
    <title>{{producto.titulo}}</title>
{% endblock %}
{% block content %}
<div class="container-fluid card">
    <div class="card-header">
        <h1>{{producto.titulo}}</h1>
    </div>
    <div class="card-body table-responsive">
        <table class="table">
            <tr>
                <td class= "p-3 m-3 col-4 ">                 
                    {% load static %}
                    <img src="{{ producto.imagen.url }}" height="300" width="300" alt="foto">
                </td>
                <td class="text-rigth text-top">
                    <p>CATEGORIA: {{producto.categoria.nombre}}</p>
                    <p>{{producto.descripcion}}</p>
                    <p>PRECIO: $ {{producto.precio}}</p>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-footer d-flex justify-content-end">
        <a href="{% url 'catalogo:index' %}">Volver al inicio</a>
        {% if perms.catalogo.change_producto %}
        <a class= "btn my-btn" href="{% url 'catalogo:producto_modificar' producto.id %}">Editar</a> 
        {% endif %}
        {% if perms.catalogo.delete_producto %} 
        <a class= "btn btn-danger" href="{% url 'catalogo:producto_eliminar' producto.id %}">Eliminar</a>  
        {% endif %}
        {% if user.is_authenticated %}
            {% if not perms.catalogo.add_producto %}
                <a class="btn my-btn align-left" href="{% url 'catalogo:agregar_carrito' producto.id %}">Agregar al carrito</a>
            {% endif %}
        {% else %}
            <a class="btn my-btn align-left" href="{% url 'login'%}?next={{request.path}}">Agregar al carrito</a>
        {% endif %}
    </div>
</div>
{% endblock %}

jaguaretekaasa/catalogo/templates/productos/producto_alta.html
{% extends "productos/layout.html" %}
{% block titulo %}
    <title>Alta de producto</title>
{% endblock %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h1>Alta de producto </h1>
    </div>
    <div class="card-body">
        <form action="{% url 'catalogo:producto_alta' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in formset %}
                <div class="container-fluid">         
                    <div class="row">
                        <div class="form-group col">
                            <label for="{{ field.name }}">{{ field.label }} 
                                {% if field.field.required %} 
                                <span class="text-danger">*</span> 
                                {% endif %}</label> 
                            </label>
                            {{ field }}
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
    <div class="card-footer d-flex justify-content-end">
        <input class="btn my-btn" type="submit" value="GUARDAR">
    </div>
    </form>
</div>
{% endblock %}

jaguaretekaasa/catalogo/templates/productos/producto_modificar.html
{% extends "productos/layout.html" %}
{% block titulo %}
    <title>Modificar producto</title>
{% endblock %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h1>Modificar producto </h1>
    </div>
    <div class="card-body">
    <form action="{% url 'catalogo:producto_modificar' un_producto.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in formset %}
            <div class="container-fluid">         
                <div class="row">
                    <div class="form-group col">
                        <label for="{{ field.name }}">{{ field.label }} 
                            {% if field.field.required %} 
                            <span class="text-danger">*</span> 
                            {% endif %}</label> 
                        </label>
                        {{ field }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="card-footer d-flex justify-content-end">
        <input class="btn my-btn" type="submit" value="GUARDAR">
    </div>
    </form>
</div>
{% endblock %}

jaguaretekaasa/catalogo/templates/productos/resultado_busqueda.html
{% extends "productos/layout.html" %}
{% block titulo %}
    <title>Resultado de la búsqueda</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h1>Listado de productos: {{item}}</h1>
        </div>
        <div class="card-body">
            {% if productos|length == 0 %}
                <h2>Ningún elemento para mostrar</h2>
            {% else %}
            <ul>
                {% for p in productos %}
                    <li><a href="{% url 'catalogo:producto' p.id %}"> {{p.titulo}}: {{p.descripcion}} </a></li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>    
{% endblock %}